-- ============================================================
-- MIGRACIÓN: perf_add_index_sessions_token_hash.sql
-- Fecha: 2026-02-26
--
-- ✅ NO EJECUTAR — YA EXISTE EN PRODUCCIÓN
--
-- La BD ya tiene los siguientes índices sobre keeper_sessions:
--   uk_keeper_sessions_tokenhash  → UNIQUE en token_hash        (O(1) auth lookup)
--   idx_sessions_token_expires    → compuesto token_hash+expires_at
--
-- Un índice UNIQUE cubre la búsqueda auth exactamente igual que
-- el índice simple que planeábamos agregar. No es necesario.
-- Intentar ejecutar el ALTER generaría un error de duplicado.
-- ============================================================

-- ALTER TABLE keeper_sessions
--   ADD INDEX idx_token_hash (token_hash);   ← YA EXISTE COMO UNIQUE
