import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { parse } from 'yaml';

const source = readFileSync(new URL('../../docs/architecture/openapi-v4.yaml', import.meta.url), 'utf8');
const schemas = parse(source, { uniqueKeys: true }).components.schemas;
const names = new Map();
const enums = new Map();
const pascal = s => s.split(/[_-]/).map(x => x[0].toUpperCase() + x.slice(1)).join('');
function type(s, hint) {
  if (s.anyOf) return type(s.anyOf.find(x => x.type !== 'null'), hint) + '?';
  if (s.$ref) { const n = s.$ref.split('/').at(-1); add(n, schemas[n]); return n; }
  if (s.enum) { enums.set(hint, s.enum); return hint; }
  if (s.type === 'object') { add(hint, s); return hint; }
  if (s.type === 'array') return `IReadOnlyList<${type(s.items, hint + 'Item')}>`;
  if (s.type === 'integer' || typeof s.const === 'number') return 'long';
  if (s.type === 'boolean') return 'bool';
  if (s.type === 'number') return 'double';
  if (s.format === 'uuid') return 'Guid';
  if (s.format === 'date-time') return 'DateTimeOffset';
  if (s.format === 'date') return 'DateOnly';
  return 'string';
}
function add(name, schema) {
  if (names.has(name)) return;
  names.set(name, '');
  const props = Object.entries(schema.properties).map(([key,s]) => {
    const required = schema.required?.includes(key);
    let t = type(s, name + pascal(key));
    if (!required && !t.endsWith('?')) t += '?';
    return `    [JsonPropertyName("${key}")]\n${required ? '    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]\n' : ''}    public ${required ? 'required ' : ''}${t} ${pascal(key)} { get; init; }`;
  });
  names.set(name, `public sealed record ${name}\n{\n${props.join('\n\n')}\n}`);
}
for (const name of ['EffectivePolicy','ChallengeRequest','Challenge','DeviceLogin','DeviceToken','SyncRequest','SyncResponse','BatchRequest','BatchAck']) add(name, schemas[name]);
const policyNames = new Set(['EffectivePolicy','Rule','Schedule','EffectivePolicyCompositionItem']);
for (const group of ['Policy','Protocol']) {
  const isPolicy = n => policyNames.has(n) || /^(Rule|EffectivePolicy)/.test(n);
  const result = `// <auto-generated />\n// OpenAPI SHA-256: ${createHash('sha256').update(source).digest('hex')}\n#nullable enable\nusing System.Text.Json.Serialization;\nusing Keeper.Shared.Policy;\n\nnamespace Keeper.Shared.${group};\n\n` +
    [...names].filter(([n]) => isPolicy(n) === (group === 'Policy')).map(([,v]) => v).join('\n\n') + '\n\n' +
    [...enums].filter(([n]) => isPolicy(n) === (group === 'Policy')).map(([n,values]) => `public enum ${n} { ${values.map(pascal).join(', ')} }`).join('\n') + '\n';
  const target = new URL(`../src/Keeper.Shared/${group}/${group}.g.cs`, import.meta.url);
  mkdirSync(new URL(`../src/Keeper.Shared/${group}/`, import.meta.url), { recursive: true });
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== result) throw new Error('Generated DTOs differ from OpenAPI');
  } else writeFileSync(target, result);
}
