// <auto-generated />
// OpenAPI SHA-256: d54e5d8b8ebb94dead40c8598d6b8f08d6f07ef8c468f0fa7c55802e4019a170
#nullable enable
using System.Text.Json.Serialization;
using Keeper.Shared.Policy;

namespace Keeper.Shared.Protocol;

public sealed record ChallengeRequest
{
    [JsonPropertyName("device_id")]
    public Guid? DeviceId { get; init; }

    [JsonPropertyName("enrollment_ticket")]
    public string? EnrollmentTicket { get; init; }
}

public sealed record Challenge
{
    [JsonPropertyName("nonce")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Nonce { get; init; }

    [JsonPropertyName("expires_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset ExpiresAt { get; init; }
}

public sealed record DeviceLogin
{
    [JsonPropertyName("device_id")]
    public Guid? DeviceId { get; init; }

    [JsonPropertyName("enrollment_ticket")]
    public string? EnrollmentTicket { get; init; }

    [JsonPropertyName("public_key")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required PublicKey PublicKey { get; init; }

    [JsonPropertyName("agent_version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string AgentVersion { get; init; }

    [JsonPropertyName("hostname")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Hostname { get; init; }
}

public sealed record PublicKey
{
    [JsonPropertyName("kty")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Kty { get; init; }

    [JsonPropertyName("crv")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Crv { get; init; }

    [JsonPropertyName("x")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string X { get; init; }

    [JsonPropertyName("y")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Y { get; init; }
}

public sealed record DeviceToken
{
    [JsonPropertyName("access_token")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string AccessToken { get; init; }

    [JsonPropertyName("token_type")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string TokenType { get; init; }

    [JsonPropertyName("expires_in")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long ExpiresIn { get; init; }

    [JsonPropertyName("device_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid DeviceId { get; init; }

    [JsonPropertyName("tenant_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid TenantId { get; init; }
}

public sealed record EnrollmentRequestInput
{
    [JsonPropertyName("enrollment_key")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string EnrollmentKey { get; init; }

    [JsonPropertyName("public_key")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required PublicKey PublicKey { get; init; }

    [JsonPropertyName("serial_number")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string? SerialNumber { get; init; }

    [JsonPropertyName("hostname")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Hostname { get; init; }

    [JsonPropertyName("agent_version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string AgentVersion { get; init; }

    [JsonPropertyName("claimed_document")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string? ClaimedDocument { get; init; }
}

public sealed record EnrollmentRequestStatus
{
    [JsonPropertyName("status")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required EnrollmentRequestStatusStatus Status { get; init; }

    [JsonPropertyName("request_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid RequestId { get; init; }

    [JsonPropertyName("enrollment_ticket")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string? EnrollmentTicket { get; init; }

    [JsonPropertyName("device_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid? DeviceId { get; init; }

    [JsonPropertyName("retry_after_seconds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long RetryAfterSeconds { get; init; }

    [JsonPropertyName("ask_document")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool AskDocument { get; init; }
}

public sealed record SyncRequest
{
    [JsonPropertyName("protocol_version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long ProtocolVersion { get; init; }

    [JsonPropertyName("sequence")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long Sequence { get; init; }

    [JsonPropertyName("policy_version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long? PolicyVersion { get; init; }

    [JsonPropertyName("release_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid? ReleaseId { get; init; }

    [JsonPropertyName("activity")]
    public ActivitySnapshot? Activity { get; init; }

    [JsonPropertyName("episodes")]
    public IReadOnlyList<Episode>? Episodes { get; init; }

    [JsonPropertyName("logs")]
    public IReadOnlyList<LogEntry>? Logs { get; init; }

    [JsonPropertyName("security")]
    public SecurityReport? Security { get; init; }

    [JsonPropertyName("inventory")]
    public DeviceInventory? Inventory { get; init; }

    [JsonPropertyName("command_results")]
    public IReadOnlyList<SyncRequestCommandResultsItem>? CommandResults { get; init; }
}

public sealed record ActivitySnapshot
{
    [JsonPropertyName("snapshot_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid SnapshotId { get; init; }

    [JsonPropertyName("sequence")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long Sequence { get; init; }

    [JsonPropertyName("day")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateOnly Day { get; init; }

    [JsonPropertyName("active_seconds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long ActiveSeconds { get; init; }

    [JsonPropertyName("idle_seconds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long IdleSeconds { get; init; }

    [JsonPropertyName("call_seconds")]
    public long? CallSeconds { get; init; }

    [JsonPropertyName("work_hours_active_seconds")]
    public long? WorkHoursActiveSeconds { get; init; }

    [JsonPropertyName("work_hours_idle_seconds")]
    public long? WorkHoursIdleSeconds { get; init; }

    [JsonPropertyName("lunch_active_seconds")]
    public long? LunchActiveSeconds { get; init; }

    [JsonPropertyName("lunch_idle_seconds")]
    public long? LunchIdleSeconds { get; init; }

    [JsonPropertyName("after_hours_active_seconds")]
    public long? AfterHoursActiveSeconds { get; init; }

    [JsonPropertyName("after_hours_idle_seconds")]
    public long? AfterHoursIdleSeconds { get; init; }

    [JsonPropertyName("first_activity_at")]
    public DateTimeOffset? FirstActivityAt { get; init; }

    [JsonPropertyName("last_activity_at")]
    public DateTimeOffset? LastActivityAt { get; init; }

    [JsonPropertyName("sample_count")]
    public long? SampleCount { get; init; }

    [JsonPropertyName("utc_offset_minutes")]
    public long? UtcOffsetMinutes { get; init; }
}

public sealed record Episode
{
    [JsonPropertyName("event_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid EventId { get; init; }

    [JsonPropertyName("started_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset StartedAt { get; init; }

    [JsonPropertyName("ended_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset EndedAt { get; init; }

    [JsonPropertyName("process_name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string ProcessName { get; init; }

    [JsonPropertyName("window_title")]
    public string? WindowTitle { get; init; }

    [JsonPropertyName("active_seconds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long ActiveSeconds { get; init; }

    [JsonPropertyName("idle_seconds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long IdleSeconds { get; init; }

    [JsonPropertyName("call_seconds")]
    public long? CallSeconds { get; init; }

    [JsonPropertyName("app_name")]
    public string? AppName { get; init; }

    [JsonPropertyName("call_app_hint")]
    public string? CallAppHint { get; init; }

    [JsonPropertyName("time_category")]
    public EpisodeTimeCategory? TimeCategory { get; init; }
}

public sealed record LogEntry
{
    [JsonPropertyName("event_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid EventId { get; init; }

    [JsonPropertyName("at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset At { get; init; }

    [JsonPropertyName("level")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required LogEntryLevel Level { get; init; }

    [JsonPropertyName("code")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Code { get; init; }

    [JsonPropertyName("component")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Component { get; init; }

    [JsonPropertyName("fields")]
    public LogEntryFields? Fields { get; init; }
}

public sealed record LogEntryFields
{
    [JsonPropertyName("control_id")]
    public string? ControlId { get; init; }

    [JsonPropertyName("command_id")]
    public Guid? CommandId { get; init; }

    [JsonPropertyName("attempt")]
    public long? Attempt { get; init; }

    [JsonPropertyName("error_code")]
    public string? ErrorCode { get; init; }
}

public sealed record SecurityReport
{
    [JsonPropertyName("event_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid EventId { get; init; }

    [JsonPropertyName("observed_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset ObservedAt { get; init; }

    [JsonPropertyName("report_hash")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string ReportHash { get; init; }

    [JsonPropertyName("controls")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<SecurityControl> Controls { get; init; }
}

public sealed record SecurityControl
{
    [JsonPropertyName("control_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string ControlId { get; init; }

    [JsonPropertyName("state")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required SecurityControlState State { get; init; }

    [JsonPropertyName("observed_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset ObservedAt { get; init; }

    [JsonPropertyName("error_code")]
    public string? ErrorCode { get; init; }
}

public sealed record DeviceInventory
{
    [JsonPropertyName("os_edition")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string OsEdition { get; init; }

    [JsonPropertyName("os_build")]
    public string? OsBuild { get; init; }

    [JsonPropertyName("cpu")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Cpu { get; init; }

    [JsonPropertyName("ram_bytes")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long RamBytes { get; init; }

    [JsonPropertyName("disk_bytes")]
    public long? DiskBytes { get; init; }

    [JsonPropertyName("serial_number")]
    public string? SerialNumber { get; init; }

    [JsonPropertyName("hostname")]
    public string? Hostname { get; init; }

    [JsonPropertyName("architecture")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DeviceInventoryArchitecture Architecture { get; init; }
}

public sealed record SyncRequestCommandResultsItem
{
    [JsonPropertyName("command_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid CommandId { get; init; }

    [JsonPropertyName("result")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required CommandResult Result { get; init; }
}

public sealed record CommandResult
{
    [JsonPropertyName("event_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid EventId { get; init; }

    [JsonPropertyName("status")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required CommandResultStatus Status { get; init; }

    [JsonPropertyName("at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset At { get; init; }

    [JsonPropertyName("code")]
    public string? Code { get; init; }
}

public sealed record SyncResponse
{
    [JsonPropertyName("protocol_version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long ProtocolVersion { get; init; }

    [JsonPropertyName("server_time")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset ServerTime { get; init; }

    [JsonPropertyName("next_sync_after_seconds")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long NextSyncAfterSeconds { get; init; }

    [JsonPropertyName("policy_version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long PolicyVersion { get; init; }

    [JsonPropertyName("policy")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required EffectivePolicy? Policy { get; init; }

    [JsonPropertyName("release")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Release? Release { get; init; }

    [JsonPropertyName("commands")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<Command> Commands { get; init; }

    [JsonPropertyName("episode_acks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<Ack> EpisodeAcks { get; init; }

    [JsonPropertyName("log_acks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<Ack> LogAcks { get; init; }

    [JsonPropertyName("security_ack")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Ack? SecurityAck { get; init; }

    [JsonPropertyName("activity_ack")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Ack? ActivityAck { get; init; }

    [JsonPropertyName("command_acks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<Ack> CommandAcks { get; init; }

    [JsonPropertyName("token")]
    public DeviceToken? Token { get; init; }
}

public sealed record Release
{
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid Id { get; init; }

    [JsonPropertyName("version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Version { get; init; }

    [JsonPropertyName("channel")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Channel { get; init; }

    [JsonPropertyName("sequence")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long Sequence { get; init; }

    [JsonPropertyName("min_agent_version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string MinAgentVersion { get; init; }

    [JsonPropertyName("architecture")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required ReleaseArchitecture Architecture { get; init; }

    [JsonPropertyName("artifact_url")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string ArtifactUrl { get; init; }

    [JsonPropertyName("size_bytes")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long SizeBytes { get; init; }

    [JsonPropertyName("sha256")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Sha256 { get; init; }

    [JsonPropertyName("key_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string KeyId { get; init; }

    [JsonPropertyName("manifest_jws")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string ManifestJws { get; init; }

    [JsonPropertyName("published_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset PublishedAt { get; init; }
}

public sealed record Command
{
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid Id { get; init; }

    [JsonPropertyName("tenant_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid TenantId { get; init; }

    [JsonPropertyName("device_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid DeviceId { get; init; }

    [JsonPropertyName("type")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required CommandType Type { get; init; }

    [JsonPropertyName("status")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required CommandStatus Status { get; init; }

    [JsonPropertyName("created_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset CreatedAt { get; init; }

    [JsonPropertyName("expires_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset ExpiresAt { get; init; }

    [JsonPropertyName("parameters")]
    public CommandParameters? Parameters { get; init; }

    [JsonPropertyName("result")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required CommandResult? Result { get; init; }
}

public sealed record CommandParameters
{
    [JsonPropertyName("computer_name")]
    public string? ComputerName { get; init; }

    [JsonPropertyName("restart_now")]
    public bool? RestartNow { get; init; }
}

public sealed record Ack
{
    [JsonPropertyName("event_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid EventId { get; init; }

    [JsonPropertyName("status")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required AckStatus Status { get; init; }

    [JsonPropertyName("code")]
    public string? Code { get; init; }

    [JsonPropertyName("retryable")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required bool Retryable { get; init; }
}

public sealed record BatchRequest
{
    [JsonPropertyName("episodes")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<Episode> Episodes { get; init; }
}

public sealed record BatchAck
{
    [JsonPropertyName("acks")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<Ack> Acks { get; init; }

    [JsonPropertyName("received_at")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required DateTimeOffset ReceivedAt { get; init; }
}

public enum EnrollmentRequestStatusStatus { Pending, Approved, Rejected, Enrolled }
public enum EpisodeTimeCategory { WorkHours, Lunch, AfterHours }
public enum LogEntryLevel { Info, Warn, Error }
public enum SecurityControlState { Applied, Failed, Unsupported, Unknown }
public enum DeviceInventoryArchitecture { X64, Arm64 }
public enum CommandResultStatus { Running, Succeeded, Failed }
public enum ReleaseArchitecture { X64, Arm64 }
public enum CommandType { Lock, Unlock, Restart, Shutdown, Wipe, RefreshPolicy, Harden, Unharden, RenameComputer }
public enum CommandStatus { Pending, Delivered, Running, Succeeded, Failed, Expired, Cancelled }
public enum AckStatus { Accepted, Duplicate, Rejected }
