// <auto-generated />
// OpenAPI SHA-256: 8d23106f676553dd2fd7b7e9d4d7bbb40bce8111f64ede7430c5813cfefd5132
#nullable enable
using System.Text.Json.Serialization;
using Keeper.Shared.Policy;

namespace Keeper.Shared.Policy;

public sealed record EffectivePolicy
{
    [JsonPropertyName("tenant_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid TenantId { get; init; }

    [JsonPropertyName("device_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid DeviceId { get; init; }

    [JsonPropertyName("version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Version { get; init; }

    [JsonPropertyName("etag")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Etag { get; init; }

    [JsonPropertyName("rules")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<Rule> Rules { get; init; }

    [JsonPropertyName("schedules")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<Schedule> Schedules { get; init; }

    [JsonPropertyName("composition")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<EffectivePolicyCompositionItem> Composition { get; init; }

    [JsonPropertyName("management_hosts")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<string> ManagementHosts { get; init; }
}

public sealed record Rule
{
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid Id { get; init; }

    [JsonPropertyName("kind")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required RuleKind Kind { get; init; }

    [JsonPropertyName("effect")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required RuleEffect Effect { get; init; }

    [JsonPropertyName("targets")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<string> Targets { get; init; }

    [JsonPropertyName("schedule_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid? ScheduleId { get; init; }

    [JsonPropertyName("priority")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long Priority { get; init; }
}

public sealed record Schedule
{
    [JsonPropertyName("id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid Id { get; init; }

    [JsonPropertyName("tenant_id")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required Guid TenantId { get; init; }

    [JsonPropertyName("name")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Name { get; init; }

    [JsonPropertyName("timezone")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Timezone { get; init; }

    [JsonPropertyName("days")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required IReadOnlyList<long> Days { get; init; }

    [JsonPropertyName("start_local")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string StartLocal { get; init; }

    [JsonPropertyName("end_local")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string EndLocal { get; init; }

    [JsonPropertyName("lunch_start_local")]
    public string? LunchStartLocal { get; init; }

    [JsonPropertyName("lunch_end_local")]
    public string? LunchEndLocal { get; init; }

    [JsonPropertyName("version")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required long Version { get; init; }
}

public sealed record EffectivePolicyCompositionItem
{
    [JsonPropertyName("level")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required EffectivePolicyCompositionItemLevel Level { get; init; }

    [JsonPropertyName("revision")]
    [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
    public required string Revision { get; init; }
}

public enum RuleKind { Web, Download, Installation, Schedule, Os, Usb, Encryption }
public enum RuleEffect { Allow, Deny, Require }
public enum EffectivePolicyCompositionItemLevel { Platform, Tenant, Site, Area, User, Device }
